##
##  Makefile -- Build procedure for sample reqcounter Apache module
##  Autogenerated via ``apxs -n reqcounter -g''.
##

apache_home=/etc/httpd
openport=11080

builddir=.
top_srcdir=/etc/httpd
arch=$(shell uname -m)
ifeq ($(arch),x86_64)
    top_builddir=/usr/lib64/httpd
else
    top_builddir=/usr/lib/httpd
endif

include $(top_builddir)/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl
FULLPERL=/usr/bin/perl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_reqcounter.o mod_reqcounter.lo mod_reqcounter.slo mod_reqcounter.la 

#   simple test
test ::
	APACHE_HOME=$(apache_home) OPEN_PORT=$(openport) PERL_DL_NONLAZY=1 $(FULLPERL) "-MExtUtils::Command::MM" "-e" "test_harness(0)" t/*.t

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
#start:
#	$(APACHECTL) start
#restart:
#	$(APACHECTL) restart
#stop:
#	$(APACHECTL) stop

